-- adder - VHDL export of JLS circuit "adder".
-- Generated by JLS @VERSION@; output is deterministic (no timestamps).
-- JLS simulates two states plus HiZ: this design drives '0'/'1'/'Z', never 'X'.
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity adder is
  port (
    a : in std_logic_vector(3 downto 0);  -- InputPin "a"
    b : in std_logic_vector(3 downto 0);  -- InputPin "b"
    cin : in std_logic;  -- InputPin "cin"
    cout : out std_logic;  -- OutputPin "cout"
    s : out std_logic_vector(3 downto 0)  -- OutputPin "s"
  );
end entity adder;

architecture structural of adder is
  signal net_3_0 : std_logic_vector(3 downto 0);
  signal net_3_1 : std_logic;
  signal net_3_0_full : unsigned(4 downto 0);
begin

  -- Adder at (96,60)
  net_3_0_full <= ('0' & unsigned(a)) + ('0' & unsigned(b)) + unsigned'(0 => cin);
  net_3_0 <= std_logic_vector(net_3_0_full(3 downto 0));
  net_3_1 <= net_3_0_full(4);

  -- OutputPin "s"
  s <= net_3_0;

  -- OutputPin "cout"
  cout <= net_3_1;

end architecture structural;
