// adder - Verilog-2005 export of JLS circuit "adder".
// Generated by JLS @VERSION@; output is deterministic (no timestamps).
// JLS simulates two states plus HiZ: this module drives 0/1/z, never x.
module adder (a, b, cin, cout, s);
  input [3:0] a;  // InputPin "a"
  input [3:0] b;  // InputPin "b"
  input cin;  // InputPin "cin"
  output cout;  // OutputPin "cout"
  output [3:0] s;  // OutputPin "s"

  wire [3:0] net_3_0;
  wire net_3_1;

  // Adder at (96,60)
  assign {net_3_1, net_3_0} = a + b + cin;

  // OutputPin "s"
  assign s = net_3_0;

  // OutputPin "cout"
  assign cout = net_3_1;

endmodule
