// bundles - Verilog-2005 export of JLS circuit "bundles".
// Generated by JLS @VERSION@; output is deterministic (no timestamps).
// JLS simulates two states plus HiZ: this module drives 0/1/z, never x.
module bundles (hi, lo, rest, top);
  input [1:0] hi;  // InputPin "hi"
  input [1:0] lo;  // InputPin "lo"
  output [2:0] rest;  // OutputPin "rest"
  output top;  // OutputPin "top"

  wire [3:0] net_2;
  wire net_3_0;
  wire [2:0] net_3_1;

  // Binder at (84,60)
  assign net_2[3:2] = hi;
  assign net_2[1:0] = lo;

  // Splitter at (96,60)
  assign net_3_0 = net_2[3];
  assign net_3_1 = net_2[2:0];

  // OutputPin "top"
  assign top = net_3_0;

  // OutputPin "rest"
  assign rest = net_3_1;

endmodule
