-- bundles - VHDL export of JLS circuit "bundles".
-- Generated by JLS @VERSION@; output is deterministic (no timestamps).
-- JLS simulates two states plus HiZ: this design drives '0'/'1'/'Z', never 'X'.
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity bundles is
  port (
    hi : in std_logic_vector(1 downto 0);  -- InputPin "hi"
    lo : in std_logic_vector(1 downto 0);  -- InputPin "lo"
    rest : out std_logic_vector(2 downto 0);  -- OutputPin "rest"
    top : out std_logic  -- OutputPin "top"
  );
end entity bundles;

architecture structural of bundles is
  signal net_2 : std_logic_vector(3 downto 0);
  signal net_3_0 : std_logic;
  signal net_3_1 : std_logic_vector(2 downto 0);
begin

  -- Binder at (84,60)
  net_2(3 downto 2) <= hi;
  net_2(1 downto 0) <= lo;

  -- Splitter at (96,60)
  net_3_0 <= net_2(3);
  net_3_1 <= net_2(2 downto 0);

  -- OutputPin "top"
  top <= net_3_0;

  -- OutputPin "rest"
  rest <= net_3_1;

end architecture structural;
