-- comb - VHDL export of JLS circuit "comb".
-- Generated by JLS @VERSION@; output is deterministic (no timestamps).
-- JLS simulates two states plus HiZ: this design drives '0'/'1'/'Z', never 'X'.
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity comb is
  port (
    a : in std_logic;  -- InputPin "a"
    b : in std_logic;  -- InputPin "b"
    c : in std_logic;  -- InputPin "c"
    y : out std_logic  -- OutputPin "y"
  );
end entity comb;

architecture structural of comb is
  signal net_3 : std_logic;
  signal net_4 : std_logic;
  signal net_5 : std_logic;
begin

  -- AndGate at (96,60)
  net_3 <= a and b;

  -- NotGate at (108,60)
  net_4 <= not c;

  -- OrGate at (120,60)
  net_5 <= net_3 or net_4;

  -- OutputPin "y"
  y <= net_5;

end architecture structural;
