// comb - Verilog-2005 export of JLS circuit "comb".
// Generated by JLS @VERSION@; output is deterministic (no timestamps).
// JLS simulates two states plus HiZ: this module drives 0/1/z, never x.
module comb (a, b, c, y);
  input a;  // InputPin "a"
  input b;  // InputPin "b"
  input c;  // InputPin "c"
  output y;  // OutputPin "y"

  wire net_3;
  wire net_4;
  wire net_5;

  // AndGate at (96,60)
  assign net_3 = a & b;

  // NotGate at (108,60)
  assign net_4 = ~c;

  // OrGate at (120,60)
  assign net_5 = net_3 | net_4;

  // OutputPin "y"
  assign y = net_5;

endmodule
