// constant - Verilog-2005 export of JLS circuit "constant".
// Generated by JLS @VERSION@; output is deterministic (no timestamps).
// JLS simulates two states plus HiZ: this module drives 0/1/z, never x.
module constant (y);
  output [3:0] y;  // OutputPin "y"

  wire [3:0] net_0;

  // Constant 11 at (60,60)
  assign net_0 = 4'hb;

  // OutputPin "y"
  assign y = net_0;

endmodule
