-- constant_v - VHDL export of JLS circuit "constant".
-- Generated by JLS @VERSION@; output is deterministic (no timestamps).
-- JLS simulates two states plus HiZ: this design drives '0'/'1'/'Z', never 'X'.
-- Name legalization (JLS name -> VHDL identifier):
--   "constant" -> constant_v
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity constant_v is
  port (
    y : out std_logic_vector(3 downto 0)  -- OutputPin "y"
  );
end entity constant_v;

architecture structural of constant_v is
  signal net_0 : std_logic_vector(3 downto 0);
begin

  -- Constant 11 at (60,60)
  net_0 <= "1011";

  -- OutputPin "y"
  y <= net_0;

end architecture structural;
