// counter - Verilog-2005 export of JLS circuit "counter".
// Generated by JLS @VERSION@; output is deterministic (no timestamps).
// JLS simulates two states plus HiZ: this module drives 0/1/z, never x.
module counter (clk, q);
  input clk;  // JLS Clock at (60,60), cycle 20 units (high 10); drive this input from the testbench
  output [3:0] q;  // OutputPin "q"

  wire [3:0] count_q;
  wire [3:0] net_1;
  wire [3:0] net_2_0;
  wire unc_2_1;
  wire [3:0] unc_3_1;

  // Constant 1 at (72,60)
  assign net_1 = 4'h1;

  // Adder at (84,60)
  assign {unc_2_1, net_2_0} = count_q + net_1 + 1'h0;

  // Register "count": 4-bit positive-edge flip-flop, initial value 0
  reg [3:0] count = 4'h0;
  always @(posedge clk) count <= net_2_0;
  assign count_q = count;
  assign unc_3_1 = ~count;

  // OutputPin "q"
  assign q = count_q;

endmodule
