-- counter - VHDL export of JLS circuit "counter".
-- Generated by JLS @VERSION@; output is deterministic (no timestamps).
-- JLS simulates two states plus HiZ: this design drives '0'/'1'/'Z', never 'X'.
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity counter is
  port (
    clk : in std_logic;  -- JLS Clock at (60,60), cycle 20 units (high 10); drive this input from the testbench
    q : out std_logic_vector(3 downto 0)  -- OutputPin "q"
  );
end entity counter;

architecture structural of counter is
  signal count_q : std_logic_vector(3 downto 0);
  signal net_1 : std_logic_vector(3 downto 0);
  signal net_2_0 : std_logic_vector(3 downto 0);
  signal unc_2_1 : std_logic;
  signal unc_3_1 : std_logic_vector(3 downto 0);
  signal net_2_0_full : unsigned(4 downto 0);
  signal count : std_logic_vector(3 downto 0) := "0000";
begin

  -- Constant 1 at (72,60)
  net_1 <= "0001";

  -- Adder at (84,60)
  net_2_0_full <= ('0' & unsigned(count_q)) + ('0' & unsigned(net_1)) + unsigned'("0");
  net_2_0 <= std_logic_vector(net_2_0_full(3 downto 0));
  unc_2_1 <= net_2_0_full(4);

  -- Register "count": 4-bit positive-edge flip-flop, initial value 0
  process (clk)
  begin
    if rising_edge(clk) then
      count <= net_2_0;
    end if;
  end process;
  count_q <= count;
  unc_3_1 <= not count;

  -- OutputPin "q"
  q <= count_q;

end architecture structural;
