// decoder - Verilog-2005 export of JLS circuit "decoder".
// Generated by JLS @VERSION@; output is deterministic (no timestamps).
// JLS simulates two states plus HiZ: this module drives 0/1/z, never x.
module decoder (d, y);
  input [1:0] d;  // InputPin "d"
  output [3:0] y;  // OutputPin "y"

  wire [3:0] net_1;

  // Decoder (2 to 4) at (72,60)
  reg [3:0] dec_1;
  always @* case (d)
    2'h0: dec_1 = 4'h1;
    2'h1: dec_1 = 4'h2;
    2'h2: dec_1 = 4'h4;
    2'h3: dec_1 = 4'h8;
    default: dec_1 = 4'h0;
  endcase
  assign net_1 = dec_1;

  // OutputPin "y"
  assign y = net_1;

endmodule
