-- decoder - VHDL export of JLS circuit "decoder".
-- Generated by JLS @VERSION@; output is deterministic (no timestamps).
-- JLS simulates two states plus HiZ: this design drives '0'/'1'/'Z', never 'X'.
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity decoder is
  port (
    d : in std_logic_vector(1 downto 0);  -- InputPin "d"
    y : out std_logic_vector(3 downto 0)  -- OutputPin "y"
  );
end entity decoder;

architecture structural of decoder is
  signal net_1 : std_logic_vector(3 downto 0);
begin

  -- Decoder (2 to 4) at (72,60)
  with d select
    net_1 <= "0001" when "00",
             "0010" when "01",
             "0100" when "10",
             "1000" when "11",
             "0000" when others;

  -- OutputPin "y"
  y <= net_1;

end architecture structural;
