// extend - Verilog-2005 export of JLS circuit "extend".
// Generated by JLS @VERSION@; output is deterministic (no timestamps).
// JLS simulates two states plus HiZ: this module drives 0/1/z, never x.
module extend (a, y);
  input a;  // InputPin "a"
  output [3:0] y;  // OutputPin "y"

  wire [3:0] net_1;

  // Extend (1 bit to 4) at (72,60)
  assign net_1 = {4{a}};

  // OutputPin "y"
  assign y = net_1;

endmodule
