-- extend - VHDL export of JLS circuit "extend".
-- Generated by JLS @VERSION@; output is deterministic (no timestamps).
-- JLS simulates two states plus HiZ: this design drives '0'/'1'/'Z', never 'X'.
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity extend is
  port (
    a : in std_logic;  -- InputPin "a"
    y : out std_logic_vector(3 downto 0)  -- OutputPin "y"
  );
end entity extend;

architecture structural of extend is
  signal net_1 : std_logic_vector(3 downto 0);
begin

  -- Extend (1 bit to 4) at (72,60)
  net_1 <= (others => a);

  -- OutputPin "y"
  y <= net_1;

end architecture structural;
