// xorgate - Verilog-2005 export of JLS circuit "xorgate".
// Generated by JLS @VERSION@; output is deterministic (no timestamps).
// JLS simulates two states plus HiZ: this module drives 0/1/z, never x.
module xorgate (a, b, y);
  input [1:0] a;  // InputPin "a"
  input [1:0] b;  // InputPin "b"
  output [1:0] y;  // OutputPin "y"

  wire [1:0] net_2;

  // XorGate at (84,60)
  assign net_2 = a ^ b;

  // OutputPin "y"
  assign y = net_2;

endmodule
