-- notgate - VHDL export of JLS circuit "notgate".
-- Generated by JLS @VERSION@; output is deterministic (no timestamps).
-- JLS simulates two states plus HiZ: this design drives '0'/'1'/'Z', never 'X'.
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity notgate is
  port (
    a : in std_logic;  -- InputPin "a"
    y : out std_logic  -- OutputPin "y"
  );
end entity notgate;

architecture structural of notgate is
  signal net_1 : std_logic;
begin

  -- NotGate at (72,60)
  net_1 <= not a;

  -- OutputPin "y"
  y <= net_1;

end architecture structural;
