// delaygate - Verilog-2005 export of JLS circuit "delaygate".
// Generated by JLS @VERSION@; output is deterministic (no timestamps).
// JLS simulates two states plus HiZ: this module drives 0/1/z, never x.
module delaygate (a, y);
  input a;  // InputPin "a"
  output y;  // OutputPin "y"

  wire net_1;

  // DelayGate at (72,60)
  assign net_1 = a;

  // OutputPin "y"
  assign y = net_1;

endmodule
