-- nandgate - VHDL export of JLS circuit "nandgate".
-- Generated by JLS @VERSION@; output is deterministic (no timestamps).
-- JLS simulates two states plus HiZ: this design drives '0'/'1'/'Z', never 'X'.
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity nandgate is
  port (
    a : in std_logic_vector(1 downto 0);  -- InputPin "a"
    b : in std_logic_vector(1 downto 0);  -- InputPin "b"
    y : out std_logic_vector(1 downto 0)  -- OutputPin "y"
  );
end entity nandgate;

architecture structural of nandgate is
  signal net_2 : std_logic_vector(1 downto 0);
begin

  -- NandGate at (84,60)
  net_2 <= not (a and b);

  -- OutputPin "y"
  y <= net_2;

end architecture structural;
