-- delaygate - VHDL export of JLS circuit "delaygate".
-- Generated by JLS @VERSION@; output is deterministic (no timestamps).
-- JLS simulates two states plus HiZ: this design drives '0'/'1'/'Z', never 'X'.
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity delaygate is
  port (
    a : in std_logic;  -- InputPin "a"
    y : out std_logic  -- OutputPin "y"
  );
end entity delaygate;

architecture structural of delaygate is
  signal net_1 : std_logic;
begin

  -- DelayGate at (72,60)
  net_1 <= a;

  -- OutputPin "y"
  y <= net_1;

end architecture structural;
