-- aliased - VHDL export of JLS circuit "aliased".
-- Generated by JLS @VERSION@; output is deterministic (no timestamps).
-- JLS simulates two states plus HiZ: this design drives '0'/'1'/'Z', never 'X'.
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity aliased is
  port (
    a : in std_logic;  -- InputPin "a"
    y : out std_logic  -- OutputPin "y"
  );
end entity aliased;

architecture structural of aliased is
  signal mid : std_logic;
  signal net_4 : std_logic;
begin

  -- NotGate at (72,60)
  mid <= not a;

  -- NotGate at (108,60)
  net_4 <= not mid;

  -- OutputPin "y"
  y <= net_4;

end architecture structural;
