// aliased - Verilog-2005 export of JLS circuit "aliased".
// Generated by JLS @VERSION@; output is deterministic (no timestamps).
// JLS simulates two states plus HiZ: this module drives 0/1/z, never x.
module aliased (a, y);
  input a;  // InputPin "a"
  output y;  // OutputPin "y"

  wire mid;
  wire net_4;

  // NotGate at (72,60)
  assign mid = ~a;

  // NotGate at (108,60)
  assign net_4 = ~mid;

  // OutputPin "y"
  assign y = net_4;

endmodule
