// keyword - Verilog-2005 export of JLS circuit "keyword".
// Generated by JLS @VERSION@; output is deterministic (no timestamps).
// JLS simulates two states plus HiZ: this module drives 0/1/z, never x.
// Name legalization (JLS name -> Verilog identifier):
//   "wire" -> wire_
module keyword (wire_, y);
  input wire_;  // InputPin "wire"
  output y;  // OutputPin "y"

  // OutputPin "y"
  assign y = wire_;

endmodule
