-- keyword - VHDL export of JLS circuit "keyword".
-- Generated by JLS @VERSION@; output is deterministic (no timestamps).
-- JLS simulates two states plus HiZ: this design drives '0'/'1'/'Z', never 'X'.
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity keyword is
  port (
    wire : in std_logic;  -- InputPin "wire"
    y : out std_logic  -- OutputPin "y"
  );
end entity keyword;

architecture structural of keyword is
begin

  -- OutputPin "y"
  y <= wire;

end architecture structural;
