-- keyword_vhdl - VHDL export of JLS circuit "keyword_vhdl".
-- Generated by JLS @VERSION@; output is deterministic (no timestamps).
-- JLS simulates two states plus HiZ: this design drives '0'/'1'/'Z', never 'X'.
-- Name legalization (JLS name -> VHDL identifier):
--   "in" -> in_v
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity keyword_vhdl is
  port (
    in_v : in std_logic;  -- InputPin "in"
    y : out std_logic  -- OutputPin "y"
  );
end entity keyword_vhdl;

architecture structural of keyword_vhdl is
begin

  -- OutputPin "y"
  y <= in_v;

end architecture structural;
