-- mux - VHDL export of JLS circuit "mux".
-- Generated by JLS @VERSION@; output is deterministic (no timestamps).
-- JLS simulates two states plus HiZ: this design drives '0'/'1'/'Z', never 'X'.
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity mux is
  port (
    a : in std_logic_vector(1 downto 0);  -- InputPin "a"
    b : in std_logic_vector(1 downto 0);  -- InputPin "b"
    sel : in std_logic;  -- InputPin "sel"
    y : out std_logic_vector(1 downto 0)  -- OutputPin "y"
  );
end entity mux;

architecture structural of mux is
  signal net_3 : std_logic_vector(1 downto 0);
begin

  -- Mux (2 inputs) at (96,60)
  with sel select
    net_3 <= a when '0',
             b when '1',
             "00" when others;

  -- OutputPin "y"
  y <= net_3;

end architecture structural;
