// mux - Verilog-2005 export of JLS circuit "mux".
// Generated by JLS @VERSION@; output is deterministic (no timestamps).
// JLS simulates two states plus HiZ: this module drives 0/1/z, never x.
module mux (a, b, sel, y);
  input [1:0] a;  // InputPin "a"
  input [1:0] b;  // InputPin "b"
  input sel;  // InputPin "sel"
  output [1:0] y;  // OutputPin "y"

  wire [1:0] net_3;

  // Mux (2 inputs) at (96,60)
  reg [1:0] mux_3;
  always @* case (sel)
    1'h0: mux_3 = a;
    1'h1: mux_3 = b;
    default: mux_3 = 2'h0;
  endcase
  assign net_3 = mux_3;

  // OutputPin "y"
  assign y = net_3;

endmodule
