// mux3 - Verilog-2005 export of JLS circuit "mux3".
// Generated by JLS @VERSION@; output is deterministic (no timestamps).
// JLS simulates two states plus HiZ: this module drives 0/1/z, never x.
module mux3 (a, b, c, sel, y);
  input a;  // InputPin "a"
  input b;  // InputPin "b"
  input c;  // InputPin "c"
  input [1:0] sel;  // InputPin "sel"
  output y;  // OutputPin "y"

  wire net_4;

  // Mux (3 inputs) at (108,60)
  reg mux_4;
  always @* case (sel)
    2'h0: mux_4 = a;
    2'h1: mux_4 = b;
    2'h2: mux_4 = c;
    default: mux_4 = 1'h0;
  endcase
  assign net_4 = mux_4;

  // OutputPin "y"
  assign y = net_4;

endmodule
