-- mux3 - VHDL export of JLS circuit "mux3".
-- Generated by JLS @VERSION@; output is deterministic (no timestamps).
-- JLS simulates two states plus HiZ: this design drives '0'/'1'/'Z', never 'X'.
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity mux3 is
  port (
    a : in std_logic;  -- InputPin "a"
    b : in std_logic;  -- InputPin "b"
    c : in std_logic;  -- InputPin "c"
    sel : in std_logic_vector(1 downto 0);  -- InputPin "sel"
    y : out std_logic  -- OutputPin "y"
  );
end entity mux3;

architecture structural of mux3 is
  signal net_4 : std_logic;
begin

  -- Mux (3 inputs) at (108,60)
  with sel select
    net_4 <= a when "00",
             b when "01",
             c when "10",
             '0' when others;

  -- OutputPin "y"
  y <= net_4;

end architecture structural;
