// reglatch - Verilog-2005 export of JLS circuit "reglatch".
// Generated by JLS @VERSION@; output is deterministic (no timestamps).
// JLS simulates two states plus HiZ: this module drives 0/1/z, never x.
module reglatch (ck, d, nq, q);
  input ck;  // InputPin "ck"
  input [3:0] d;  // InputPin "d"
  output [3:0] nq;  // OutputPin "nq"
  output [3:0] q;  // OutputPin "q"

  wire [3:0] r_nq;
  wire [3:0] r_q;

  // Register "r": 4-bit transparent latch, initial value 5
  reg [3:0] r = 4'h5;
  always @(ck or d) if (ck) r = d;
  assign r_q = r;
  assign r_nq = ~r;

  // OutputPin "q"
  assign q = r_q;

  // OutputPin "nq"
  assign nq = r_nq;

endmodule
