-- regnff - VHDL export of JLS circuit "regnff".
-- Generated by JLS @VERSION@; output is deterministic (no timestamps).
-- JLS simulates two states plus HiZ: this design drives '0'/'1'/'Z', never 'X'.
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity regnff is
  port (
    ck : in std_logic;  -- InputPin "ck"
    d : in std_logic_vector(3 downto 0);  -- InputPin "d"
    nq : out std_logic_vector(3 downto 0);  -- OutputPin "nq"
    q : out std_logic_vector(3 downto 0)  -- OutputPin "q"
  );
end entity regnff;

architecture structural of regnff is
  signal r_nq : std_logic_vector(3 downto 0);
  signal r_q : std_logic_vector(3 downto 0);
  signal r : std_logic_vector(3 downto 0) := "0101";
begin

  -- Register "r": 4-bit negative-edge flip-flop, initial value 5
  process (ck)
  begin
    if falling_edge(ck) then
      r <= d;
    end if;
  end process;
  r_q <= r;
  r_nq <= not r;

  -- OutputPin "q"
  q <= r_q;

  -- OutputPin "nq"
  nq <= r_nq;

end architecture structural;
