-- regpff - VHDL export of JLS circuit "regpff".
-- Generated by JLS @VERSION@; output is deterministic (no timestamps).
-- JLS simulates two states plus HiZ: this design drives '0'/'1'/'Z', never 'X'.
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity regpff is
  port (
    d : in std_logic_vector(3 downto 0);  -- InputPin "d"
    clk : in std_logic;  -- JLS Clock at (72,60), cycle 20 units (high 10); drive this input from the testbench
    nq : out std_logic_vector(3 downto 0);  -- OutputPin "nq"
    q : out std_logic_vector(3 downto 0)  -- OutputPin "q"
  );
end entity regpff;

architecture structural of regpff is
  signal r_nq : std_logic_vector(3 downto 0);
  signal r_q : std_logic_vector(3 downto 0);
  signal r : std_logic_vector(3 downto 0) := "0101";
begin

  -- Register "r": 4-bit positive-edge flip-flop, initial value 5
  process (clk)
  begin
    if rising_edge(clk) then
      r <= d;
    end if;
  end process;
  r_q <= r;
  r_nq <= not r;

  -- OutputPin "q"
  q <= r_q;

  -- OutputPin "nq"
  nq <= r_nq;

end architecture structural;
