-- shiftright - VHDL export of JLS circuit "shiftright".
-- Generated by JLS @VERSION@; output is deterministic (no timestamps).
-- JLS simulates two states plus HiZ: this design drives '0'/'1'/'Z', never 'X'.
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity shiftright is
  port (
    a : in std_logic_vector(7 downto 0);  -- InputPin "a"
    amt : in std_logic_vector(2 downto 0);  -- InputPin "amt"
    y : out std_logic_vector(7 downto 0)  -- OutputPin "y"
  );
end entity shiftright;

architecture structural of shiftright is
  signal net_2 : std_logic_vector(7 downto 0);
begin

  -- ShiftRegister (8-bit logical right) at (84,60)
  net_2 <= std_logic_vector(shift_right(unsigned(a), to_integer(unsigned(amt))));

  -- OutputPin "y"
  y <= net_2;

end architecture structural;
