// shiftleft - Verilog-2005 export of JLS circuit "shiftleft".
// Generated by JLS @VERSION@; output is deterministic (no timestamps).
// JLS simulates two states plus HiZ: this module drives 0/1/z, never x.
module shiftleft (a, amt, y);
  input [7:0] a;  // InputPin "a"
  input [2:0] amt;  // InputPin "amt"
  output [7:0] y;  // OutputPin "y"

  wire [7:0] net_2;

  // ShiftRegister (8-bit logical left) at (84,60)
  assign net_2 = a << amt;

  // OutputPin "y"
  assign y = net_2;

endmodule
