-- statemachine_else - VHDL export of JLS circuit "statemachine_else".
-- Generated by JLS @VERSION@; output is deterministic (no timestamps).
-- JLS simulates two states plus HiZ: this design drives '0'/'1'/'Z', never 'X'.
-- Name legalization (JLS name -> VHDL identifier):
--   "on" -> on_v
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity statemachine_else is
  port (
    ck : in std_logic;  -- InputPin "ck"
    sel : in std_logic_vector(1 downto 0);  -- InputPin "sel"
    on_v : out std_logic;  -- OutputPin "on"
    phase : out std_logic_vector(1 downto 0)  -- OutputPin "phase"
  );
end entity statemachine_else;

architecture structural of statemachine_else is
  signal net_2_0 : std_logic;
  signal net_2_1 : std_logic_vector(1 downto 0);
  signal seq_state : std_logic_vector(1 downto 0) := "00";
begin

  -- StateMachine "seq" (falling edge, 3 states) at (84,60): state codes "start"=0, "mid"=1, "stop"=2; an edge matching no transition holds the state (issue #98). Divergences: JLS ignores edges during its 30-unit transition window (busy), this export never does; JLS picks among simultaneously matching conditions in hash order, this export tests them in canonical (#180) order
  process (ck)
  begin
    if falling_edge(ck) then
      case seq_state is
        when "00" =>  -- "start"
          if sel /= "10" then
            seq_state <= "01";
          else
            seq_state <= "10";
          end if;
        when "01" =>  -- "mid"
          if sel = "00" then
            seq_state <= "00";
          else
            seq_state <= "10";
          end if;
        when "10" =>  -- "stop": always
          seq_state <= "00";
        when others =>  -- non-state codes: the state holds
          null;
      end case;
    end if;
  end process;
  process (seq_state)
  begin
    case seq_state is
      when "00" =>  -- "start"
        net_2_0 <= '0';
        net_2_1 <= "00";
      when "01" =>  -- "mid"
        net_2_0 <= '1';
        net_2_1 <= "01";
      when "10" =>  -- "stop"
        net_2_0 <= '0';
        net_2_1 <= "10";
      when others =>  -- unreachable codes read 0
        net_2_0 <= '0';
        net_2_1 <= "00";
    end case;
  end process;

  -- OutputPin "phase"
  phase <= net_2_1;

  -- OutputPin "on"
  on_v <= net_2_0;

end architecture structural;
