-- statemachine_hold - VHDL export of JLS circuit "statemachine_hold".
-- Generated by JLS @VERSION@; output is deterministic (no timestamps).
-- JLS simulates two states plus HiZ: this design drives '0'/'1'/'Z', never 'X'.
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity statemachine_hold is
  port (
    ck : in std_logic;  -- InputPin "ck"
    go : in std_logic;  -- InputPin "go"
    colour : out std_logic_vector(1 downto 0)  -- OutputPin "colour"
  );
end entity statemachine_hold;

architecture structural of statemachine_hold is
  signal net_2 : std_logic_vector(1 downto 0);
  signal light_state : std_logic_vector(1 downto 0) := "00";
begin

  -- StateMachine "light" (rising edge, 3 states) at (84,60): state codes "red"=0, "green"=1, "yellow"=2; an edge matching no transition holds the state (issue #98). Divergences: JLS ignores edges during its 30-unit transition window (busy), this export never does; JLS picks among simultaneously matching conditions in hash order, this export tests them in canonical (#180) order
  process (ck)
  begin
    if rising_edge(ck) then
      case light_state is
        when "00" =>  -- "red"
          if go = '1' then
            light_state <= "01";
          end if;  -- no else: an unmatched input holds the state
        when "01" =>  -- "green"
          if go = '0' then
            light_state <= "10";
          end if;  -- no else: an unmatched input holds the state
        when "10" =>  -- "yellow": no transitions, the state holds
          null;
        when others =>  -- non-state codes: the state holds
          null;
      end case;
    end if;
  end process;
  process (light_state)
  begin
    case light_state is
      when "00" =>  -- "red"
        net_2 <= "00";
      when "01" =>  -- "green"
        net_2 <= "01";
      when "10" =>  -- "yellow"
        net_2 <= "10";
      when others =>  -- unreachable codes read 0
        net_2 <= "00";
    end case;
  end process;

  -- OutputPin "colour"
  colour <= net_2;

end architecture structural;
