// statemachine - Verilog-2005 export of JLS circuit "statemachine".
// Generated by JLS @VERSION@; output is deterministic (no timestamps).
// JLS simulates two states plus HiZ: this module drives 0/1/z, never x.
module statemachine (go, clk, done);
  input go;  // InputPin "go"
  input clk;  // JLS Clock at (60,60), cycle 20 units (high 10); drive this input from the testbench
  output done;  // OutputPin "done"

  wire net_2;

  // StateMachine "ctrl" (rising edge, 2 states) at (84,60): state codes "idle"=0, "run"=1; an edge matching no transition holds the state (issue #98). Divergences: JLS ignores edges during its 30-unit transition window (busy), this export never does; JLS picks among simultaneously matching conditions in hash order, this export tests them in canonical (#180) order
  reg ctrl_state = 1'h0;
  always @(posedge clk) case (ctrl_state)
    1'h0: begin  // "idle"
      if (go == 1'h1) ctrl_state <= 1'h1;
      // no else: an unmatched input holds the state
    end
    1'h1: ctrl_state <= 1'h0;  // "run": always
  endcase
  reg sm_2_0;
  always @* case (ctrl_state)
    1'h0: sm_2_0 = 1'h0;
    1'h1: sm_2_0 = 1'h1;
    default: sm_2_0 = 1'h0;
  endcase
  assign net_2 = sm_2_0;

  // OutputPin "done"
  assign done = net_2;

endmodule
