// statemachine_else - Verilog-2005 export of JLS circuit "statemachine_else".
// Generated by JLS @VERSION@; output is deterministic (no timestamps).
// JLS simulates two states plus HiZ: this module drives 0/1/z, never x.
module statemachine_else (ck, sel, on, phase);
  input ck;  // InputPin "ck"
  input [1:0] sel;  // InputPin "sel"
  output on;  // OutputPin "on"
  output [1:0] phase;  // OutputPin "phase"

  wire net_2_0;
  wire [1:0] net_2_1;

  // StateMachine "seq" (falling edge, 3 states) at (84,60): state codes "start"=0, "mid"=1, "stop"=2; an edge matching no transition holds the state (issue #98). Divergences: JLS ignores edges during its 30-unit transition window (busy), this export never does; JLS picks among simultaneously matching conditions in hash order, this export tests them in canonical (#180) order
  reg [1:0] seq_state = 2'h0;
  always @(negedge ck) case (seq_state)
    2'h0: begin  // "start"
      if (sel != 2'h2) seq_state <= 2'h1;
      else seq_state <= 2'h2;
    end
    2'h1: begin  // "mid"
      if (sel == 2'h0) seq_state <= 2'h0;
      else seq_state <= 2'h2;
    end
    2'h2: seq_state <= 2'h0;  // "stop": always
  endcase
  reg sm_2_0;
  reg [1:0] sm_2_1;
  always @* case (seq_state)
    2'h0: begin sm_2_0 = 1'h0; sm_2_1 = 2'h0; end
    2'h1: begin sm_2_0 = 1'h1; sm_2_1 = 2'h1; end
    2'h2: begin sm_2_0 = 1'h0; sm_2_1 = 2'h2; end
    default: begin sm_2_0 = 1'h0; sm_2_1 = 2'h0; end
  endcase
  assign net_2_0 = sm_2_0;
  assign net_2_1 = sm_2_1;

  // OutputPin "phase"
  assign phase = net_2_1;

  // OutputPin "on"
  assign on = net_2_0;

endmodule
