// statemachine_hold - Verilog-2005 export of JLS circuit "statemachine_hold".
// Generated by JLS @VERSION@; output is deterministic (no timestamps).
// JLS simulates two states plus HiZ: this module drives 0/1/z, never x.
module statemachine_hold (ck, go, colour);
  input ck;  // InputPin "ck"
  input go;  // InputPin "go"
  output [1:0] colour;  // OutputPin "colour"

  wire [1:0] net_2;

  // StateMachine "light" (rising edge, 3 states) at (84,60): state codes "red"=0, "green"=1, "yellow"=2; an edge matching no transition holds the state (issue #98). Divergences: JLS ignores edges during its 30-unit transition window (busy), this export never does; JLS picks among simultaneously matching conditions in hash order, this export tests them in canonical (#180) order
  reg [1:0] light_state = 2'h0;
  always @(posedge ck) case (light_state)
    2'h0: begin  // "red"
      if (go == 1'h1) light_state <= 2'h1;
      // no else: an unmatched input holds the state
    end
    2'h1: begin  // "green"
      if (go == 1'h0) light_state <= 2'h2;
      // no else: an unmatched input holds the state
    end
    2'h2: ;  // "yellow": no transitions, the state holds
  endcase
  reg [1:0] sm_2_0;
  always @* case (light_state)
    2'h0: sm_2_0 = 2'h0;
    2'h1: sm_2_0 = 2'h1;
    2'h2: sm_2_0 = 2'h2;
    default: sm_2_0 = 2'h0;
  endcase
  assign net_2 = sm_2_0;

  // OutputPin "colour"
  assign colour = net_2;

endmodule
