-- statemachine - VHDL export of JLS circuit "statemachine".
-- Generated by JLS @VERSION@; output is deterministic (no timestamps).
-- JLS simulates two states plus HiZ: this design drives '0'/'1'/'Z', never 'X'.
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity statemachine is
  port (
    go : in std_logic;  -- InputPin "go"
    clk : in std_logic;  -- JLS Clock at (60,60), cycle 20 units (high 10); drive this input from the testbench
    done : out std_logic  -- OutputPin "done"
  );
end entity statemachine;

architecture structural of statemachine is
  signal net_2 : std_logic;
  signal ctrl_state : std_logic := '0';
begin

  -- StateMachine "ctrl" (rising edge, 2 states) at (84,60): state codes "idle"=0, "run"=1; an edge matching no transition holds the state (issue #98). Divergences: JLS ignores edges during its 30-unit transition window (busy), this export never does; JLS picks among simultaneously matching conditions in hash order, this export tests them in canonical (#180) order
  process (clk)
  begin
    if rising_edge(clk) then
      case ctrl_state is
        when '0' =>  -- "idle"
          if go = '1' then
            ctrl_state <= '1';
          end if;  -- no else: an unmatched input holds the state
        when '1' =>  -- "run": always
          ctrl_state <= '0';
        when others =>  -- non-state codes: the state holds
          null;
      end case;
    end if;
  end process;
  process (ctrl_state)
  begin
    case ctrl_state is
      when '0' =>  -- "idle"
        net_2 <= '0';
      when '1' =>  -- "run"
        net_2 <= '1';
      when others =>  -- unreachable codes read 0
        net_2 <= '0';
    end case;
  end process;

  -- OutputPin "done"
  done <= net_2;

end architecture structural;
