-- tristate - VHDL export of JLS circuit "tristate".
-- Generated by JLS @VERSION@; output is deterministic (no timestamps).
-- JLS simulates two states plus HiZ: this design drives '0'/'1'/'Z', never 'X'.
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity tristate is
  port (
    a : in std_logic_vector(3 downto 0);  -- InputPin "a"
    en : in std_logic;  -- InputPin "en"
    y : out std_logic_vector(3 downto 0)  -- OutputPin "y"
  );
end entity tristate;

architecture structural of tristate is
  signal net_2 : std_logic_vector(3 downto 0);
begin

  -- TriState at (84,60)
  net_2 <= a when en = '1' else (others => 'Z');

  -- OutputPin "y"
  y <= net_2;

end architecture structural;
