// tristate - Verilog-2005 export of JLS circuit "tristate".
// Generated by JLS @VERSION@; output is deterministic (no timestamps).
// JLS simulates two states plus HiZ: this module drives 0/1/z, never x.
module tristate (a, en, y);
  input [3:0] a;  // InputPin "a"
  input en;  // InputPin "en"
  output [3:0] y;  // OutputPin "y"

  wire [3:0] net_2;

  // TriState at (84,60)
  assign net_2 = en ? a : 4'bz;

  // OutputPin "y"
  assign y = net_2;

endmodule
