-- truthtable_multiout - VHDL export of JLS circuit "truthtable_multiout".
-- Generated by JLS @VERSION@; output is deterministic (no timestamps).
-- JLS simulates two states plus HiZ: this design drives '0'/'1'/'Z', never 'X'.
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity truthtable_multiout is
  port (
    s : in std_logic;  -- InputPin "s"
    p : out std_logic;  -- OutputPin "p"
    q : out std_logic  -- OutputPin "q"
  );
end entity truthtable_multiout;

architecture structural of truthtable_multiout is
  signal net_1_0 : std_logic;
  signal net_1_1 : std_logic;
  signal net_1_0_tt : std_logic_vector(0 downto 0);
begin

  -- TruthTable "split" (1 in, 2 out, 2 rows) at (72,60): first matching row wins; no match holds the outputs (JLS also drives row 0 at startup)
  net_1_0_tt(0) <= s;
  process (net_1_0_tt)
  begin
    if std_match(net_1_0_tt, "0") then
      net_1_0 <= '0';
      net_1_1 <= '1';
    elsif std_match(net_1_0_tt, "1") then
      net_1_0 <= '1';
      net_1_1 <= '0';
    end if;  -- no else: an unmatched input vector holds the prior outputs
  end process;

  -- OutputPin "p"
  p <= net_1_0;

  -- OutputPin "q"
  q <= net_1_1;

end architecture structural;
