// truthtable - Verilog-2005 export of JLS circuit "truthtable".
// Generated by JLS @VERSION@; output is deterministic (no timestamps).
// JLS simulates two states plus HiZ: this module drives 0/1/z, never x.
module truthtable (a, b, y);
  input a;  // InputPin "a"
  input b;  // InputPin "b"
  output y;  // OutputPin "y"

  wire net_2;

  // TruthTable "xorish" (2 in, 1 out, 3 rows) at (84,60): first matching row wins; no match holds the outputs (JLS also drives row 0 at startup)
  reg tt_2_0;
  always @* casez ({a, b})
    2'b00: tt_2_0 = 1'h0;
    2'b01: tt_2_0 = 1'h1;
    2'b10: tt_2_0 = 1'h1;
    // no default arm: an unmatched input vector holds the prior outputs
  endcase
  assign net_2 = tt_2_0;

  // OutputPin "y"
  assign y = net_2;

endmodule
