// truthtable_multiout - Verilog-2005 export of JLS circuit "truthtable_multiout".
// Generated by JLS @VERSION@; output is deterministic (no timestamps).
// JLS simulates two states plus HiZ: this module drives 0/1/z, never x.
module truthtable_multiout (s, p, q);
  input s;  // InputPin "s"
  output p;  // OutputPin "p"
  output q;  // OutputPin "q"

  wire net_1_0;
  wire net_1_1;

  // TruthTable "split" (1 in, 2 out, 2 rows) at (72,60): first matching row wins; no match holds the outputs (JLS also drives row 0 at startup)
  reg tt_1_0;
  reg tt_1_1;
  always @* casez ({s})
    1'b0: begin tt_1_0 = 1'h0; tt_1_1 = 1'h1; end
    1'b1: begin tt_1_0 = 1'h1; tt_1_1 = 1'h0; end
    // no default arm: an unmatched input vector holds the prior outputs
  endcase
  assign net_1_0 = tt_1_0;
  assign net_1_1 = tt_1_1;

  // OutputPin "p"
  assign p = net_1_0;

  // OutputPin "q"
  assign q = net_1_1;

endmodule
