-- truthtable - VHDL export of JLS circuit "truthtable".
-- Generated by JLS @VERSION@; output is deterministic (no timestamps).
-- JLS simulates two states plus HiZ: this design drives '0'/'1'/'Z', never 'X'.
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity truthtable is
  port (
    a : in std_logic;  -- InputPin "a"
    b : in std_logic;  -- InputPin "b"
    y : out std_logic  -- OutputPin "y"
  );
end entity truthtable;

architecture structural of truthtable is
  signal net_2 : std_logic;
  signal net_2_tt : std_logic_vector(1 downto 0);
begin

  -- TruthTable "xorish" (2 in, 1 out, 3 rows) at (84,60): first matching row wins; no match holds the outputs (JLS also drives row 0 at startup)
  net_2_tt <= a & b;
  process (net_2_tt)
  begin
    if std_match(net_2_tt, "00") then
      net_2 <= '0';
    elsif std_match(net_2_tt, "01") then
      net_2 <= '1';
    elsif std_match(net_2_tt, "10") then
      net_2 <= '1';
    end if;  -- no else: an unmatched input vector holds the prior outputs
  end process;

  -- OutputPin "y"
  y <= net_2;

end architecture structural;
