package jls.hdl;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

/**
 * Renders an {@link HdlModel} as Verilog-2005 (issue #60): one
 * structural/dataflow module per circuit, deterministic byte-for-byte
 * output (no timestamps), pinned by golden tests. Style choices:
 * continuous assigns for combinational elements, one {@code reg} plus
 * an {@code always} block per Register, declaration-time initial
 * values ({@code reg [3:0] r = 4'h5;}, Verilog-2001), and 0/1/z only
 * — JLS never simulates x, so the export never drives it.
 */
public final class VerilogEmitter implements HdlEmitter {

	/** Creates the (stateless) emitter. */
	public VerilogEmitter() {
	} // end of VerilogEmitter constructor

	/**
	 * Renders the elaborated model as one complete Verilog module.
	 * @param model the HDL model (ports, nets, statements) to export
	 * @return the module source text, deterministic and self-contained
	 * @see jls.hdl.HdlPolicyTest#twoNetsBridgedByJumpsBecomeOneVerilogNet()
	 */
	@Override
	public String emit(HdlModel model) {

		StringBuilder out = new StringBuilder();
		header(out, model);
		moduleHeader(out, model);
		portDeclarations(out, model);
		netDeclarations(out, model);
		for (HdlModel.Statement statement : model.statements()) {
			statement(out, statement);
		}
		out.append("\nendmodule\n");
		return out.toString();
	} // end of emit method

	/**
	 * The file extension for Verilog output.
	 * @return {@code "v"}
	 */
	@Override
	public String fileExtension() {

		return "v";
	} // end of fileExtension method

	// ------------------------------------------------------------------
	// module framing
	// ------------------------------------------------------------------

	/**
	 * Emits the leading comment banner: module name, source circuit,
	 * the determinism/state note, and the name-legalization legend.
	 * @param out the buffer the module text is appended to
	 * @param model the model supplying names and renames
	 */
	private static void header(StringBuilder out, HdlModel model) {

		out.append("// ").append(model.moduleName)
				.append(" - Verilog-2005 export of JLS circuit \"")
				.append(model.sourceCircuitName).append("\".\n");
		out.append("// Generated by JLS ").append(model.jlsVersion)
				.append("; output is deterministic (no timestamps).\n");
		out.append("// JLS simulates two states plus HiZ:")
				.append(" this module drives 0/1/z, never x.\n");
		Map<String, String> renames = model.renames();
		if (!renames.isEmpty()) {
			out.append("// Name legalization (JLS name -> Verilog"
					+ " identifier):\n");
			for (Map.Entry<String, String> entry : renames.entrySet()) {
				out.append("//   \"").append(entry.getKey()).append("\" -> ")
						.append(entry.getValue()).append('\n');
			}
		}
	} // end of header method

	/**
	 * Emits the {@code module name (ports);} declaration line.
	 * @param out the buffer the module text is appended to
	 * @param model the model supplying the module name and port list
	 */
	private static void moduleHeader(StringBuilder out, HdlModel model) {

		out.append("module ").append(model.moduleName);
		List<String> portNames = new ArrayList<String>();
		for (HdlModel.Port port : model.ports()) {
			portNames.add(port.name);
		}
		if (!portNames.isEmpty()) {
			out.append(" (").append(String.join(", ", portNames))
					.append(')');
		}
		out.append(";\n");
	} // end of moduleHeader method

	/**
	 * Emits one {@code input}/{@code output} declaration per port.
	 * @param out the buffer the module text is appended to
	 * @param model the model supplying the ports
	 */
	private static void portDeclarations(StringBuilder out, HdlModel model) {

		for (HdlModel.Port port : model.ports()) {
			out.append("  ").append(
					port.direction == HdlModel.Direction.INPUT
							? "input" : "output")
					.append(range(port.bits)).append(' ').append(port.name)
					.append(';');
			if (port.comment != null) {
				out.append("  // ").append(port.comment);
			}
			out.append('\n');
		}
	} // end of portDeclarations method

	/**
	 * Emits a {@code wire} declaration for each internal net; a no-op
	 * when the model has none.
	 * @param out the buffer the module text is appended to
	 * @param model the model supplying the nets
	 */
	private static void netDeclarations(StringBuilder out, HdlModel model) {

		if (model.nets().isEmpty()) {
			return;
		}
		out.append('\n');
		for (HdlModel.Net net : model.nets()) {
			out.append("  wire").append(range(net.bits)).append(' ')
					.append(net.name).append(";\n");
		}
	} // end of netDeclarations method

	/**
	 * Renders a declaration's bit range.
	 * @param bits width of the declared port, net, or reg
	 * @return {@code " [msb:0]"} for multi-bit, {@code ""} for scalar
	 */
	private static String range(int bits) {

		return bits > 1 ? " [" + (bits - 1) + ":0]" : "";
	} // end of range method

	// ------------------------------------------------------------------
	// statements
	// ------------------------------------------------------------------

	/**
	 * Emits any leading comment then dispatches the statement to the
	 * Verilog template for its concrete kind (double-dispatch visitor).
	 * @param out the buffer the module text is appended to
	 * @param statement the statement to render
	 */
	private static void statement(StringBuilder out,
			HdlModel.Statement statement) {

		if (statement.comment != null) {
			out.append("\n  // ").append(statement.comment).append('\n');
		}
		// dispatch by double-dispatch: a new statement kind fails to
		// compile until this visitor grows a template for it
		statement.accept(new HdlModel.StatementVisitor() {
			/** Routes a gate statement to {@link #gate}. */
			@Override
			public void visit(HdlModel.GateStatement s) {
				gate(out, s);
			}
			/** Routes a replicate statement to {@link #replicate}. */
			@Override
			public void visit(HdlModel.ReplicateStatement s) {
				replicate(out, s);
			}
			/** Routes a constant statement to {@link #constant}. */
			@Override
			public void visit(HdlModel.ConstantStatement s) {
				constant(out, s);
			}
			/** Routes a tri-state statement to {@link #triState}. */
			@Override
			public void visit(HdlModel.TriStateStatement s) {
				triState(out, s);
			}
			/** Routes an adder statement to {@link #adder}. */
			@Override
			public void visit(HdlModel.AdderStatement s) {
				adder(out, s);
			}
			/** Routes a register statement to {@link #register}. */
			@Override
			public void visit(HdlModel.RegisterStatement s) {
				register(out, s);
			}
			/** Routes a bit-map statement to {@link #bitMap}. */
			@Override
			public void visit(HdlModel.BitMapStatement s) {
				bitMap(out, s);
			}
			/** Routes a select statement to {@link #select}. */
			@Override
			public void visit(HdlModel.SelectStatement s) {
				select(out, s);
			}
		});
	} // end of statement method

	/**
	 * Emits a continuous {@code assign} for a logic-gate statement,
	 * choosing the Verilog operator for the gate's operation.
	 * @param out the buffer the module text is appended to
	 * @param s the gate statement (operation, inputs, output net)
	 */
	private static void gate(StringBuilder out, HdlModel.GateStatement s) {

		String joined;
		switch (s.op) {
		case AND:
			joined = join(s.inputs, " & ");
			break;
		case OR:
			joined = join(s.inputs, " | ");
			break;
		case XOR:
			joined = join(s.inputs, " ^ ");
			break;
		case NAND:
			joined = "~(" + join(s.inputs, " & ") + ")";
			break;
		case NOR:
			joined = "~(" + join(s.inputs, " | ") + ")";
			break;
		case NOT:
			joined = "~" + operand(s.inputs.get(0));
			break;
		default: // BUFFER
			joined = operand(s.inputs.get(0));
			break;
		}
		out.append("  assign ").append(s.output).append(" = ").append(joined)
				.append(";\n");
	} // end of gate method

	/**
	 * Emits a continuous {@code assign} replicating a single input a
	 * given number of times ({@code {n{x}}}).
	 * @param out the buffer the module text is appended to
	 * @param s the replicate statement (input, repeat count, output)
	 */
	private static void replicate(StringBuilder out,
			HdlModel.ReplicateStatement s) {

		out.append("  assign ").append(s.output).append(" = {").append(s.bits)
				.append('{').append(operand(s.input)).append("}};\n");
	} // end of replicate method

	/**
	 * Emits a continuous {@code assign} of a sized literal value.
	 * @param out the buffer the module text is appended to
	 * @param s the constant statement (value, width, output net)
	 */
	private static void constant(StringBuilder out,
			HdlModel.ConstantStatement s) {

		out.append("  assign ").append(s.output).append(" = ")
				.append(literal(s.value, s.bits)).append(";\n");
	} // end of constant method

	/**
	 * Emits a continuous {@code assign} of a tri-state driver: the input
	 * when the control is high, high-impedance ({@code 'bz}) otherwise.
	 * @param out the buffer the module text is appended to
	 * @param s the tri-state statement (control, input, output net)
	 */
	private static void triState(StringBuilder out,
			HdlModel.TriStateStatement s) {

		out.append("  assign ").append(s.output).append(" = ")
				.append(operand(s.control)).append(" ? ")
				.append(operand(s.input)).append(" : ").append(s.bits)
				.append("'bz;\n");
	} // end of triState method

	/**
	 * Emits a continuous {@code assign} summing the two operands and the
	 * carry-in into the concatenated {@code {carryOut, sum}}.
	 * @param out the buffer the module text is appended to
	 * @param s the adder statement (operands, carry-in/out, sum net)
	 */
	private static void adder(StringBuilder out, HdlModel.AdderStatement s) {

		out.append("  assign {").append(s.carryOut).append(", ")
				.append(s.sum).append("} = ").append(operand(s.a))
				.append(" + ").append(operand(s.b)).append(" + ")
				.append(operand(s.carryIn)).append(";\n");
	} // end of adder method

	/**
	 * Emits a register: its {@code reg} declaration with initial value,
	 * an {@code always} block for the clock kind (posedge/negedge/latch,
	 * or a comment when no clock is connected), and the q/notQ assigns.
	 * @param out the buffer the module text is appended to
	 * @param s the register statement (clock, kind, data, outputs)
	 */
	private static void register(StringBuilder out,
			HdlModel.RegisterStatement s) {

		out.append("  reg").append(range(s.bits)).append(' ')
				.append(s.regName).append(" = ")
				.append(literal(s.initial, s.bits)).append(";\n");
		if (s.clock.isNet()) {
			String clock = s.clock.netName();
			switch (s.kind) {
			case POS_EDGE:
				out.append("  always @(posedge ").append(clock).append(") ")
						.append(s.regName).append(" <= ")
						.append(operand(s.d)).append(";\n");
				break;
			case NEG_EDGE:
				out.append("  always @(negedge ").append(clock).append(") ")
						.append(s.regName).append(" <= ")
						.append(operand(s.d)).append(";\n");
				break;
			default: // LATCH: transparent while the clock is 1
				out.append("  always @(").append(clock);
				if (s.d.isNet()) {
					out.append(" or ").append(s.d.netName());
				}
				out.append(") if (").append(clock).append(") ")
						.append(s.regName).append(" = ")
						.append(operand(s.d)).append(";\n");
				break;
			}
		}
		else {
			// an unconnected clock never ticks: the register holds its
			// initial value (matches JLS; the walker warned already)
			out.append("  // no clock connected: ").append(s.regName)
					.append(" holds its initial value\n");
		}
		out.append("  assign ").append(s.q).append(" = ").append(s.regName)
				.append(";\n");
		out.append("  assign ").append(s.notQ).append(" = ~")
				.append(s.regName).append(";\n");
	} // end of register method

	/**
	 * Emits a selected assignment (Mux/Decoder, the #59-adjudicated
	 * {@code case} template): a helper {@code reg} assigned in an
	 * {@code always @*} {@code case} over the selector - one arm per
	 * value, a {@code default} arm for everything else - then a
	 * continuous {@code assign} of the helper onto the target net.
	 * @param out the buffer the module text is appended to
	 * @param s the select statement (selector, values, default, target)
	 */
	private static void select(StringBuilder out, HdlModel.SelectStatement s) {

		out.append("  reg").append(range(s.bits)).append(' ')
				.append(s.helperName).append(";\n");
		out.append("  always @* case (").append(operand(s.selector))
				.append(")\n");
		for (int i = 0; i < s.values.size(); i += 1) {
			out.append("    ")
					.append(literal(BigInteger.valueOf(i), s.selector.bits()))
					.append(": ").append(s.helperName).append(" = ")
					.append(operand(s.values.get(i))).append(";\n");
		}
		out.append("    default: ").append(s.helperName).append(" = ")
				.append(operand(s.defaultValue)).append(";\n");
		out.append("  endcase\n");
		out.append("  assign ").append(s.target).append(" = ")
				.append(s.helperName).append(";\n");
	} // end of select method

	/**
	 * Bit routing, with contiguous runs coalesced into part-selects:
	 * target[targetIndex[i]] = source[sourceIndex[i]].
	 * @param out the buffer the module text is appended to
	 * @param s the bit-map statement (source, target, index arrays)
	 */
	private static void bitMap(StringBuilder out, HdlModel.BitMapStatement s) {

		int[] src = s.sourceIndex();
		int[] dst = s.targetIndex();
		int i = 0;
		while (i < src.length) {
			int j = i;
			while (j + 1 < src.length && src[j + 1] == src[j] + 1
					&& dst[j + 1] == dst[j] + 1) {
				j += 1;
			}
			out.append("  assign ")
					.append(select(s.target, s.targetBits, dst[i], dst[j]))
					.append(" = ").append(sourceSelect(s, src[i], src[j]))
					.append(";\n");
			i = j + 1;
		}
	} // end of bitMap method

	/**
	 * Renders the source side of a bit-map run: a net part-select, or a
	 * sized literal slice when the source is a constant.
	 * @param s the bit-map statement whose source is being read
	 * @param lo the low source bit index of the run
	 * @param hi the high source bit index of the run
	 * @return the Verilog expression for that source slice
	 */
	private static String sourceSelect(HdlModel.BitMapStatement s, int lo,
			int hi) {

		if (s.source.isNet()) {
			return select(s.source.netName(), s.source.bits(), lo, hi);
		}
		BigInteger slice = s.source.literalValue().shiftRight(lo);
		return literal(slice, hi - lo + 1);
	} // end of sourceSelect method

	/**
	 * Renders a whole net, one bit, or a part-select, as narrow as legal.
	 * @param name the net or port name
	 * @param declaredBits the declared width of the net
	 * @param lo the low bit index of the run
	 * @param hi the high bit index of the run
	 * @return the narrowest legal Verilog select expression
	 */
	private static String select(String name, int declaredBits, int lo,
			int hi) {

		if (declaredBits == 1 || (lo == 0 && hi == declaredBits - 1)) {
			return name;
		}
		if (lo == hi) {
			return name + "[" + lo + "]";
		}
		return name + "[" + hi + ":" + lo + "]";
	} // end of select method

	// ------------------------------------------------------------------
	// operands
	// ------------------------------------------------------------------

	/**
	 * Renders an operand as either its net name or a sized literal.
	 * @param o the operand (net reference or constant value)
	 * @return the Verilog expression for the operand
	 */
	private static String operand(HdlModel.Operand o) {

		return o.isNet() ? o.netName() : literal(o.literalValue(), o.bits());
	} // end of operand method

	/**
	 * Renders a sized hex literal, masked to its width (e.g. 4'hb).
	 * @param value the literal value
	 * @param bits the literal's width in bits
	 * @return the sized Verilog hex literal
	 */
	private static String literal(BigInteger value, int bits) {

		BigInteger mask = BigInteger.ONE.shiftLeft(bits)
				.subtract(BigInteger.ONE);
		return bits + "'h" + value.and(mask).toString(16);
	} // end of literal method

	/**
	 * Renders a list of operands joined by a separator.
	 * @param operands the operands to render, in order
	 * @param separator the text placed between rendered operands
	 * @return the concatenated expression string
	 */
	private static String join(List<HdlModel.Operand> operands,
			String separator) {

		StringBuilder sb = new StringBuilder();
		for (HdlModel.Operand o : operands) {
			if (sb.length() > 0) {
				sb.append(separator);
			}
			sb.append(operand(o));
		}
		return sb.toString();
	} // end of join method

} // end of VerilogEmitter class
