package jls.hdl;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

/**
 * Renders an {@link HdlModel} as Verilog-2005 (issue #60): one
 * structural/dataflow module per circuit, deterministic byte-for-byte
 * output (no timestamps), pinned by golden tests. Style choices:
 * continuous assigns for combinational elements, one {@code reg} plus
 * an {@code always} block per Register, declaration-time initial
 * values ({@code reg [3:0] r = 4'h5;}, Verilog-2001), and 0/1/z only
 * — JLS never simulates x, so the export never drives it.
 */
public final class VerilogEmitter implements HdlEmitter {

	public String emit(HdlModel model) {

		StringBuilder out = new StringBuilder();
		header(out, model);
		moduleHeader(out, model);
		portDeclarations(out, model);
		netDeclarations(out, model);
		for (HdlModel.Statement statement : model.statements()) {
			statement(out, statement);
		}
		out.append("\nendmodule\n");
		return out.toString();
	} // end of emit method

	public String fileExtension() {

		return "v";
	} // end of fileExtension method

	// ------------------------------------------------------------------
	// module framing
	// ------------------------------------------------------------------

	private static void header(StringBuilder out, HdlModel model) {

		out.append("// ").append(model.moduleName)
				.append(" - Verilog-2005 export of JLS circuit \"")
				.append(model.sourceCircuitName).append("\".\n");
		out.append("// Generated by JLS ").append(model.jlsVersion)
				.append("; output is deterministic (no timestamps).\n");
		out.append("// JLS simulates two states plus HiZ:")
				.append(" this module drives 0/1/z, never x.\n");
		Map<String, String> renames = model.renames();
		if (!renames.isEmpty()) {
			out.append("// Name legalization (JLS name -> Verilog"
					+ " identifier):\n");
			for (Map.Entry<String, String> entry : renames.entrySet()) {
				out.append("//   \"").append(entry.getKey()).append("\" -> ")
						.append(entry.getValue()).append('\n');
			}
		}
	} // end of header method

	private static void moduleHeader(StringBuilder out, HdlModel model) {

		out.append("module ").append(model.moduleName);
		List<String> portNames = new ArrayList<String>();
		for (HdlModel.Port port : model.ports()) {
			portNames.add(port.name);
		}
		if (!portNames.isEmpty()) {
			out.append(" (").append(String.join(", ", portNames))
					.append(')');
		}
		out.append(";\n");
	} // end of moduleHeader method

	private static void portDeclarations(StringBuilder out, HdlModel model) {

		for (HdlModel.Port port : model.ports()) {
			out.append("  ").append(
					port.direction == HdlModel.Direction.INPUT
							? "input" : "output")
					.append(range(port.bits)).append(' ').append(port.name)
					.append(';');
			if (port.comment != null) {
				out.append("  // ").append(port.comment);
			}
			out.append('\n');
		}
	} // end of portDeclarations method

	private static void netDeclarations(StringBuilder out, HdlModel model) {

		if (model.nets().isEmpty()) {
			return;
		}
		out.append('\n');
		for (HdlModel.Net net : model.nets()) {
			out.append("  wire").append(range(net.bits)).append(' ')
					.append(net.name).append(";\n");
		}
	} // end of netDeclarations method

	/** " [msb:0]" for multi-bit, "" for scalar. */
	private static String range(int bits) {

		return bits > 1 ? " [" + (bits - 1) + ":0]" : "";
	} // end of range method

	// ------------------------------------------------------------------
	// statements
	// ------------------------------------------------------------------

	private static void statement(StringBuilder out,
			HdlModel.Statement statement) {

		if (statement.comment != null) {
			out.append("\n  // ").append(statement.comment).append('\n');
		}
		if (statement instanceof HdlModel.GateStatement) {
			gate(out, (HdlModel.GateStatement) statement);
		}
		else if (statement instanceof HdlModel.ReplicateStatement) {
			replicate(out, (HdlModel.ReplicateStatement) statement);
		}
		else if (statement instanceof HdlModel.ConstantStatement) {
			constant(out, (HdlModel.ConstantStatement) statement);
		}
		else if (statement instanceof HdlModel.TriStateStatement) {
			triState(out, (HdlModel.TriStateStatement) statement);
		}
		else if (statement instanceof HdlModel.AdderStatement) {
			adder(out, (HdlModel.AdderStatement) statement);
		}
		else if (statement instanceof HdlModel.RegisterStatement) {
			register(out, (HdlModel.RegisterStatement) statement);
		}
		else if (statement instanceof HdlModel.BitMapStatement) {
			bitMap(out, (HdlModel.BitMapStatement) statement);
		}
		else {
			throw new IllegalStateException(
					"no Verilog template for " + statement.getClass());
		}
	} // end of statement method

	private static void gate(StringBuilder out, HdlModel.GateStatement s) {

		String joined;
		switch (s.op) {
		case AND:
			joined = join(s.inputs, " & ");
			break;
		case OR:
			joined = join(s.inputs, " | ");
			break;
		case XOR:
			joined = join(s.inputs, " ^ ");
			break;
		case NAND:
			joined = "~(" + join(s.inputs, " & ") + ")";
			break;
		case NOR:
			joined = "~(" + join(s.inputs, " | ") + ")";
			break;
		case NOT:
			joined = "~" + operand(s.inputs.get(0));
			break;
		default: // BUFFER
			joined = operand(s.inputs.get(0));
			break;
		}
		out.append("  assign ").append(s.output).append(" = ").append(joined)
				.append(";\n");
	} // end of gate method

	private static void replicate(StringBuilder out,
			HdlModel.ReplicateStatement s) {

		out.append("  assign ").append(s.output).append(" = {").append(s.bits)
				.append('{').append(operand(s.input)).append("}};\n");
	} // end of replicate method

	private static void constant(StringBuilder out,
			HdlModel.ConstantStatement s) {

		out.append("  assign ").append(s.output).append(" = ")
				.append(literal(s.value, s.bits)).append(";\n");
	} // end of constant method

	private static void triState(StringBuilder out,
			HdlModel.TriStateStatement s) {

		out.append("  assign ").append(s.output).append(" = ")
				.append(operand(s.control)).append(" ? ")
				.append(operand(s.input)).append(" : ").append(s.bits)
				.append("'bz;\n");
	} // end of triState method

	private static void adder(StringBuilder out, HdlModel.AdderStatement s) {

		out.append("  assign {").append(s.carryOut).append(", ")
				.append(s.sum).append("} = ").append(operand(s.a))
				.append(" + ").append(operand(s.b)).append(" + ")
				.append(operand(s.carryIn)).append(";\n");
	} // end of adder method

	private static void register(StringBuilder out,
			HdlModel.RegisterStatement s) {

		out.append("  reg").append(range(s.bits)).append(' ')
				.append(s.regName).append(" = ")
				.append(literal(s.initial, s.bits)).append(";\n");
		if (s.clock.isNet()) {
			String clock = s.clock.netName();
			switch (s.kind) {
			case POS_EDGE:
				out.append("  always @(posedge ").append(clock).append(") ")
						.append(s.regName).append(" <= ")
						.append(operand(s.d)).append(";\n");
				break;
			case NEG_EDGE:
				out.append("  always @(negedge ").append(clock).append(") ")
						.append(s.regName).append(" <= ")
						.append(operand(s.d)).append(";\n");
				break;
			default: // LATCH: transparent while the clock is 1
				out.append("  always @(").append(clock);
				if (s.d.isNet()) {
					out.append(" or ").append(s.d.netName());
				}
				out.append(") if (").append(clock).append(") ")
						.append(s.regName).append(" = ")
						.append(operand(s.d)).append(";\n");
				break;
			}
		}
		else {
			// an unconnected clock never ticks: the register holds its
			// initial value (matches JLS; the walker warned already)
			out.append("  // no clock connected: ").append(s.regName)
					.append(" holds its initial value\n");
		}
		out.append("  assign ").append(s.q).append(" = ").append(s.regName)
				.append(";\n");
		out.append("  assign ").append(s.notQ).append(" = ~")
				.append(s.regName).append(";\n");
	} // end of register method

	/**
	 * Bit routing, with contiguous runs coalesced into part-selects:
	 * target[targetIndex[i]] = source[sourceIndex[i]].
	 */
	private static void bitMap(StringBuilder out, HdlModel.BitMapStatement s) {

		int[] src = s.sourceIndex();
		int[] dst = s.targetIndex();
		int i = 0;
		while (i < src.length) {
			int j = i;
			while (j + 1 < src.length && src[j + 1] == src[j] + 1
					&& dst[j + 1] == dst[j] + 1) {
				j += 1;
			}
			out.append("  assign ")
					.append(select(s.target, s.targetBits, dst[i], dst[j]))
					.append(" = ").append(sourceSelect(s, src[i], src[j]))
					.append(";\n");
			i = j + 1;
		}
	} // end of bitMap method

	private static String sourceSelect(HdlModel.BitMapStatement s, int lo,
			int hi) {

		if (s.source.isNet()) {
			return select(s.source.netName(), s.source.bits(), lo, hi);
		}
		BigInteger slice = s.source.literalValue().shiftRight(lo);
		return literal(slice, hi - lo + 1);
	} // end of sourceSelect method

	/** A whole net, one bit, or a part-select, as narrow as legal. */
	private static String select(String name, int declaredBits, int lo,
			int hi) {

		if (declaredBits == 1 || (lo == 0 && hi == declaredBits - 1)) {
			return name;
		}
		if (lo == hi) {
			return name + "[" + lo + "]";
		}
		return name + "[" + hi + ":" + lo + "]";
	} // end of select method

	// ------------------------------------------------------------------
	// operands
	// ------------------------------------------------------------------

	private static String operand(HdlModel.Operand o) {

		return o.isNet() ? o.netName() : literal(o.literalValue(), o.bits());
	} // end of operand method

	/** A sized hex literal, masked to its width (e.g. 4'hb). */
	private static String literal(BigInteger value, int bits) {

		BigInteger mask = BigInteger.ONE.shiftLeft(bits)
				.subtract(BigInteger.ONE);
		return bits + "'h" + value.and(mask).toString(16);
	} // end of literal method

	private static String join(List<HdlModel.Operand> operands,
			String separator) {

		StringBuilder sb = new StringBuilder();
		for (HdlModel.Operand o : operands) {
			if (sb.length() > 0) {
				sb.append(separator);
			}
			sb.append(operand(o));
		}
		return sb.toString();
	} // end of join method

} // end of VerilogEmitter class
