package jls.hdl;

import java.math.BigInteger;
import java.util.Arrays;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * Renders an {@link HdlModel} as VHDL (issue #60), accepted by both
 * VHDL-93 and VHDL-2002 analyzers: one entity plus one structural/
 * dataflow architecture per circuit, deterministic byte-for-byte output
 * (no timestamps), pinned by golden tests. It consumes the same model
 * the Verilog emitter does - all circuit-walking policy (element
 * support, jump aliasing, net naming, unattached-input zeros) lives in
 * {@link HdlExporter} and is therefore identical across languages.
 * Style choices mirror {@link VerilogEmitter} construct for construct:
 * concurrent assignments for combinational elements, one state signal
 * plus a process per Register, declaration-time initial values, and
 * '0'/'1'/'Z' only - JLS never simulates 'X', so the export never
 * drives it.
 *
 * <p>Type mapping: 1-bit values are {@code std_logic}, wider values
 * {@code std_logic_vector(n-1 downto 0)}; the Adder uses a
 * {@code numeric_std unsigned} helper signal because VHDL has no
 * concatenated-target concurrent assignment.</p>
 *
 * <p>Model identifiers arrive legalized for Verilog ({@link HdlNames});
 * this emitter applies the additional pass VHDL needs - collapse and
 * trim underscores, dodge VHDL reserved words (suffix {@code _v}) and
 * the ieee package names this file references, and uniquify
 * case-insensitively - and documents every resulting change in the
 * generated header alongside the walker's own renames.</p>
 */
public final class VhdlEmitter implements HdlEmitter {

	/** Creates the (stateless) emitter. */
	public VhdlEmitter() {
	} // end of VhdlEmitter constructor

	/**
	 * Renders the model as one complete VHDL source file: comment header,
	 * ieee use clauses, entity and structural architecture.
	 * @param model the exporter-prepared circuit model to render
	 * @return the full VHDL source text
	 */
	@Override
	public String emit(HdlModel model) {

		Names names = new Names(model);

		// statements render into the architecture body, and some also
		// into its declarative part (register state, adder helpers)
		StringBuilder declarations = new StringBuilder();
		StringBuilder body = new StringBuilder();
		for (HdlModel.Statement statement : model.statements()) {
			statement(declarations, body, statement, names);
		}

		StringBuilder out = new StringBuilder();
		header(out, model, names);
		out.append("library ieee;\n");
		out.append("use ieee.std_logic_1164.all;\n");
		out.append("use ieee.numeric_std.all;\n\n");
		entity(out, model, names);
		architecture(out, model, names, declarations, body);
		return out.toString();
	} // end of emit method

	/** The output file extension for VHDL, without a leading dot. */
	@Override
	public String fileExtension() {

		return "vhdl";
	} // end of fileExtension method

	// ------------------------------------------------------------------
	// design-unit framing
	// ------------------------------------------------------------------

	/**
	 * Writes the comment header: module title, JLS version, the two-state
	 * note, and every documented name legalization.
	 * @param out sink for the generated text
	 * @param model the circuit model being rendered
	 * @param names the legalized-identifier table for this model
	 */
	private static void header(StringBuilder out, HdlModel model,
			Names names) {

		out.append("-- ").append(names.moduleName)
				.append(" - VHDL export of JLS circuit \"")
				.append(model.sourceCircuitName).append("\".\n");
		out.append("-- Generated by JLS ").append(model.jlsVersion)
				.append("; output is deterministic (no timestamps).\n");
		out.append("-- JLS simulates two states plus HiZ:")
				.append(" this design drives '0'/'1'/'Z', never 'X'.\n");
		Map<String, String> renames = names.documentedRenames(model);
		if (!renames.isEmpty()) {
			out.append("-- Name legalization (JLS name -> VHDL"
					+ " identifier):\n");
			for (Map.Entry<String, String> entry : renames.entrySet()) {
				out.append("--   \"").append(entry.getKey()).append("\" -> ")
						.append(entry.getValue()).append('\n');
			}
		}
	} // end of header method

	/**
	 * Writes the entity declaration with its port list.
	 * @param out sink for the generated text
	 * @param model the circuit model whose ports are declared
	 * @param names the legalized-identifier table for this model
	 */
	private static void entity(StringBuilder out, HdlModel model,
			Names names) {

		out.append("entity ").append(names.moduleName).append(" is\n");
		List<HdlModel.Port> ports = model.ports();
		if (!ports.isEmpty()) {
			out.append("  port (\n");
			for (int p = 0; p < ports.size(); p += 1) {
				HdlModel.Port port = ports.get(p);
				out.append("    ").append(names.of(port.name)).append(" : ")
						.append(port.direction == HdlModel.Direction.INPUT
								? "in " : "out ")
						.append(type(port.bits));
				if (p < ports.size() - 1) {
					out.append(';');
				}
				if (port.comment != null) {
					out.append("  -- ").append(port.comment);
				}
				out.append('\n');
			}
			out.append("  );\n");
		}
		out.append("end entity ").append(names.moduleName).append(";\n\n");
	} // end of entity method

	/**
	 * Writes the architecture: net signal declarations, the collected
	 * helper declarations, then the concurrent/process body.
	 * @param out sink for the generated text
	 * @param model the circuit model whose nets are declared
	 * @param names the legalized-identifier table for this model
	 * @param declarations declarative-part text gathered while rendering
	 * @param body architecture-body text gathered while rendering
	 */
	private static void architecture(StringBuilder out, HdlModel model,
			Names names, StringBuilder declarations, StringBuilder body) {

		out.append("architecture structural of ").append(names.moduleName)
				.append(" is\n");
		for (HdlModel.Net net : model.nets()) {
			out.append("  signal ").append(names.of(net.name)).append(" : ")
					.append(type(net.bits)).append(";\n");
		}
		out.append(declarations);
		out.append("begin\n");
		out.append(body);
		out.append("\nend architecture structural;\n");
	} // end of architecture method

	/**
	 * Renders the VHDL type for a value width.
	 * @param bits the declared width in bits
	 * @return {@code "std_logic_vector(msb downto 0)"} for multi-bit,
	 * else {@code "std_logic"}
	 */
	private static String type(int bits) {

		return bits > 1
				? "std_logic_vector(" + (bits - 1) + " downto 0)"
				: "std_logic";
	} // end of type method

	// ------------------------------------------------------------------
	// statements
	// ------------------------------------------------------------------

	/**
	 * Dispatches one model statement to the matching VHDL template,
	 * appending to the declarative part and/or the architecture body.
	 * @param declarations sink for declarative-part text
	 * @param body sink for architecture-body text
	 * @param statement the model statement to render
	 * @param names the legalized-identifier table for this model
	 */
	private static void statement(StringBuilder declarations,
			StringBuilder body, HdlModel.Statement statement, Names names) {

		if (statement.comment != null) {
			body.append("\n  -- ").append(statement.comment).append('\n');
		}
		// dispatch by double-dispatch: a new statement kind fails to
		// compile until this visitor grows a template for it
		statement.accept(new HdlModel.StatementVisitor() {
			/** Renders a gate statement into the body. */
			@Override
			public void visit(HdlModel.GateStatement s) {
				gate(body, s, names);
			}
			/** Renders a replicate statement into the body. */
			@Override
			public void visit(HdlModel.ReplicateStatement s) {
				replicate(body, s, names);
			}
			/** Renders a constant statement into the body. */
			@Override
			public void visit(HdlModel.ConstantStatement s) {
				constant(body, s, names);
			}
			/** Renders a tri-state statement into the body. */
			@Override
			public void visit(HdlModel.TriStateStatement s) {
				triState(body, s, names);
			}
			/** Renders an adder statement into declarations and body. */
			@Override
			public void visit(HdlModel.AdderStatement s) {
				adder(declarations, body, s, names);
			}
			/** Renders a register statement into declarations and body. */
			@Override
			public void visit(HdlModel.RegisterStatement s) {
				register(declarations, body, s, names);
			}
			/** Renders a bit-map statement into the body. */
			@Override
			public void visit(HdlModel.BitMapStatement s) {
				bitMap(body, s, names);
			}
		});
	} // end of statement method

	/**
	 * Emits a concurrent assignment for a logic gate; NAND and NOR are
	 * rendered as negated conjunctions/disjunctions because VHDL's nand
	 * and nor operators do not chain across more than two operands.
	 * @param out sink for the architecture-body text
	 * @param s the gate statement to render
	 * @param names the legalized-identifier table for this model
	 */
	private static void gate(StringBuilder out, HdlModel.GateStatement s,
			Names names) {

		String joined;
		switch (s.op) {
		case AND:
			joined = join(s.inputs, " and ", names);
			break;
		case OR:
			joined = join(s.inputs, " or ", names);
			break;
		case XOR:
			joined = join(s.inputs, " xor ", names);
			break;
		case NAND:
			// "a nand b nand c" is not legal VHDL (nand does not chain),
			// so the n-input form is not (a and b and c), like Verilog's
			// ~(a & b & c)
			joined = "not (" + join(s.inputs, " and ", names) + ")";
			break;
		case NOR:
			joined = "not (" + join(s.inputs, " or ", names) + ")";
			break;
		case NOT:
			joined = "not " + operand(s.inputs.get(0), names);
			break;
		default: // BUFFER
			joined = operand(s.inputs.get(0), names);
			break;
		}
		out.append("  ").append(names.of(s.output)).append(" <= ")
				.append(joined).append(";\n");
	} // end of gate method

	/**
	 * Emits a concurrent assignment that fans one input bit out across
	 * the full output width.
	 * @param out sink for the architecture-body text
	 * @param s the replicate statement to render
	 * @param names the legalized-identifier table for this model
	 */
	private static void replicate(StringBuilder out,
			HdlModel.ReplicateStatement s, Names names) {

		out.append("  ").append(names.of(s.output)).append(" <= ");
		if (s.bits > 1) {
			out.append("(others => ").append(operand(s.input, names))
					.append(')');
		}
		else {
			out.append(operand(s.input, names));
		}
		out.append(";\n");
	} // end of replicate method

	/**
	 * Emits a concurrent assignment driving the output with a literal.
	 * @param out sink for the architecture-body text
	 * @param s the constant statement to render
	 * @param names the legalized-identifier table for this model
	 */
	private static void constant(StringBuilder out,
			HdlModel.ConstantStatement s, Names names) {

		out.append("  ").append(names.of(s.output)).append(" <= ")
				.append(literal(s.value, s.bits)).append(";\n");
	} // end of constant method

	/**
	 * Emits a conditional assignment driving the input while the control
	 * is '1', otherwise high-impedance ('Z').
	 * @param out sink for the architecture-body text
	 * @param s the tri-state statement to render
	 * @param names the legalized-identifier table for this model
	 */
	private static void triState(StringBuilder out,
			HdlModel.TriStateStatement s, Names names) {

		out.append("  ").append(names.of(s.output)).append(" <= ")
				.append(operand(s.input, names)).append(" when ")
				.append(operand(s.control, names)).append(" = '1' else ")
				.append(s.bits > 1 ? "(others => 'Z')" : "'Z'")
				.append(";\n");
	} // end of triState method

	/**
	 * Emits the adder: a helper unsigned signal holds the bits+1-wide
	 * sum, whose low slice feeds the sum output and whose top bit feeds
	 * carry-out, since VHDL has no concatenated-target assignment.
	 * @param declarations sink for the helper signal declaration
	 * @param body sink for the architecture-body text
	 * @param s the adder statement to render
	 * @param names the legalized-identifier table for this model
	 */
	private static void adder(StringBuilder declarations, StringBuilder body,
			HdlModel.AdderStatement s, Names names) {

		// VHDL has no {carry, sum} concatenated assignment target, so
		// the bits+1-wide result lands in a helper signal first;
		// numeric_std "+" zero-extends the narrower operand
		String full = names.synth(names.of(s.sum) + "_full");
		declarations.append("  signal ").append(full).append(" : unsigned(")
				.append(s.bits).append(" downto 0);\n");
		body.append("  ").append(full).append(" <= ('0' & ")
				.append(unsigned(s.a, names)).append(") + ('0' & ")
				.append(unsigned(s.b, names)).append(") + ")
				.append(unsigned(s.carryIn, names)).append(";\n");
		body.append("  ").append(names.of(s.sum)).append(" <= ");
		if (s.bits > 1) {
			body.append("std_logic_vector(").append(full).append('(')
					.append(s.bits - 1).append(" downto 0))");
		}
		else {
			body.append(full).append("(0)");
		}
		body.append(";\n");
		body.append("  ").append(names.of(s.carryOut)).append(" <= ")
				.append(full).append('(').append(s.bits).append(");\n");
	} // end of adder method

	/**
	 * Emits a register: an initialized state signal, its clocking process
	 * (rising/falling edge or transparent latch) or a hold comment when
	 * no clock is connected, and the q and notQ output assignments.
	 * @param declarations sink for the state-signal declaration
	 * @param body sink for the process and output assignments
	 * @param s the register statement to render
	 * @param names the legalized-identifier table for this model
	 */
	private static void register(StringBuilder declarations,
			StringBuilder body, HdlModel.RegisterStatement s, Names names) {

		String reg = names.of(s.regName);
		declarations.append("  signal ").append(reg).append(" : ")
				.append(type(s.bits)).append(" := ")
				.append(literal(s.initial, s.bits)).append(";\n");
		if (s.clock.isNet()) {
			String clock = names.of(s.clock.netName());
			switch (s.kind) {
			case POS_EDGE:
				process(body, clock, null,
						"if rising_edge(" + clock + ") then",
						reg + " <= " + operand(s.d, names) + ";");
				break;
			case NEG_EDGE:
				process(body, clock, null,
						"if falling_edge(" + clock + ") then",
						reg + " <= " + operand(s.d, names) + ";");
				break;
			default: // LATCH: transparent while the clock is 1
				process(body, clock,
						s.d.isNet() ? names.of(s.d.netName()) : null,
						"if " + clock + " = '1' then",
						reg + " <= " + operand(s.d, names) + ";");
				break;
			}
		}
		else {
			// an unconnected clock never ticks: the register holds its
			// initial value (matches JLS; the walker warned already)
			body.append("  -- no clock connected: ").append(reg)
					.append(" holds its initial value\n");
		}
		body.append("  ").append(names.of(s.q)).append(" <= ").append(reg)
				.append(";\n");
		body.append("  ").append(names.of(s.notQ)).append(" <= not ")
				.append(reg).append(";\n");
	} // end of register method

	/**
	 * One-condition register process, shared by all three kinds.
	 * @param out sink for the architecture-body text
	 * @param clock the clock signal in the sensitivity list
	 * @param data extra sensitivity-list signal (latch data), or null
	 * @param condition the {@code if ... then} guard line
	 * @param assignment the guarded state assignment
	 */
	private static void process(StringBuilder out, String clock, String data,
			String condition, String assignment) {

		out.append("  process (").append(clock);
		if (data != null) {
			out.append(", ").append(data);
		}
		out.append(")\n  begin\n    ").append(condition).append("\n      ")
				.append(assignment).append("\n    end if;\n")
				.append("  end process;\n");
	} // end of process method

	/**
	 * Bit routing, with contiguous runs coalesced into slices:
	 * target(targetIndex[i]) = source(sourceIndex[i]).
	 * @param out sink for the architecture-body text
	 * @param s the bit-map statement to render
	 * @param names the legalized-identifier table for this model
	 */
	private static void bitMap(StringBuilder out, HdlModel.BitMapStatement s,
			Names names) {

		int[] src = s.sourceIndex();
		int[] dst = s.targetIndex();
		int i = 0;
		while (i < src.length) {
			int j = i;
			while (j + 1 < src.length && src[j + 1] == src[j] + 1
					&& dst[j + 1] == dst[j] + 1) {
				j += 1;
			}
			out.append("  ")
					.append(select(names.of(s.target), s.targetBits, dst[i],
							dst[j]))
					.append(" <= ").append(sourceSelect(s, src[i], src[j],
							names))
					.append(";\n");
			i = j + 1;
		}
	} // end of bitMap method

	/**
	 * The source side of a bit-map run: a slice of the source net, or a
	 * right-shifted sized literal when the source is a constant.
	 * @param s the bit-map statement being rendered
	 * @param lo low bit index of the run (inclusive)
	 * @param hi high bit index of the run (inclusive)
	 * @param names the legalized-identifier table for this model
	 * @return the VHDL expression for the selected source bits
	 */
	private static String sourceSelect(HdlModel.BitMapStatement s, int lo,
			int hi, Names names) {

		if (s.source.isNet()) {
			return select(names.of(s.source.netName()), s.source.bits(), lo,
					hi);
		}
		BigInteger slice = s.source.literalValue().shiftRight(lo);
		return literal(slice, hi - lo + 1);
	} // end of sourceSelect method

	/**
	 * Renders a whole signal, one bit, or a slice, as narrow as legal.
	 * @param name the signal name
	 * @param declaredBits the declared width of the signal
	 * @param lo the low bit index of the run
	 * @param hi the high bit index of the run
	 * @return the narrowest legal VHDL select expression
	 */
	private static String select(String name, int declaredBits, int lo,
			int hi) {

		if (declaredBits == 1 || (lo == 0 && hi == declaredBits - 1)) {
			return name;
		}
		if (lo == hi) {
			return name + "(" + lo + ")";
		}
		return name + "(" + hi + " downto " + lo + ")";
	} // end of select method

	// ------------------------------------------------------------------
	// operands
	// ------------------------------------------------------------------

	/**
	 * An operand as an ordinary VHDL expression: a net's identifier or a
	 * width-sized literal.
	 * @param o the operand to render
	 * @param names the legalized-identifier table for this model
	 * @return the VHDL expression for the operand
	 */
	private static String operand(HdlModel.Operand o, Names names) {

		return o.isNet() ? names.of(o.netName())
				: literal(o.literalValue(), o.bits());
	} // end of operand method

	/**
	 * The operand as a numeric_std unsigned expression of its width.
	 * @param o the operand to render
	 * @param names the legalized-identifier table for this model
	 * @return the VHDL unsigned expression for the operand
	 */
	private static String unsigned(HdlModel.Operand o, Names names) {

		if (!o.isNet()) {
			return "unsigned'(\"" + bitString(o.literalValue(), o.bits())
					+ "\")";
		}
		if (o.bits() > 1) {
			return "unsigned(" + names.of(o.netName()) + ")";
		}
		// a qualified single-element aggregate lifts the scalar
		return "unsigned'(0 => " + names.of(o.netName()) + ")";
	} // end of unsigned method

	/**
	 * Renders a VHDL literal of a known width.
	 * @param value the literal value
	 * @param bits the literal's width in bits
	 * @return '0'/'1' for a scalar, a sized binary string for a vector
	 */
	private static String literal(BigInteger value, int bits) {

		if (bits == 1) {
			return value.testBit(0) ? "'1'" : "'0'";
		}
		return '"' + bitString(value, bits) + '"';
	} // end of literal method

	/**
	 * Renders a value in binary.
	 * @param value the value to render
	 * @param bits the width to render at
	 * @return the value as exactly {@code bits} binary digits, masked
	 */
	private static String bitString(BigInteger value, int bits) {

		StringBuilder sb = new StringBuilder(bits);
		for (int b = bits - 1; b >= 0; b -= 1) {
			sb.append(value.testBit(b) ? '1' : '0');
		}
		return sb.toString();
	} // end of bitString method

	/**
	 * The operands rendered and concatenated with the given separator.
	 * @param operands the operands to render
	 * @param separator the text placed between rendered operands
	 * @param names the legalized-identifier table for this model
	 * @return the joined VHDL expression
	 */
	private static String join(List<HdlModel.Operand> operands,
			String separator, Names names) {

		StringBuilder sb = new StringBuilder();
		for (HdlModel.Operand o : operands) {
			if (sb.length() > 0) {
				sb.append(separator);
			}
			sb.append(operand(o, names));
		}
		return sb.toString();
	} // end of join method

	// ------------------------------------------------------------------
	// VHDL identifier legalization (second pass over model names)
	// ------------------------------------------------------------------

	/**
	 * Maps every model identifier (already Verilog-legal) to a VHDL
	 * identifier, deterministically and collision-free. The extra rules
	 * VHDL imposes: no leading, trailing or doubled underscores; no
	 * (case-insensitive) reserved words; and identifiers that differ
	 * only in case collide. Names are claimed in a fixed order - module
	 * name, ports, nets, register state variables - then synthesized
	 * helper names, so output is stable.
	 */
	private static final class Names {

		/**
		 * VHDL-93 reserved words plus "protected" (VHDL-2000/2002), plus
		 * the ieee identifiers this emitter's output references - a
		 * signal named "rising_edge" would shadow the function its own
		 * register template calls.
		 */
		private static final Set<String> RESERVED = new HashSet<String>(
				Arrays.asList(
				"abs", "access", "after", "alias", "all", "and",
				"architecture", "array", "assert", "attribute", "begin",
				"block", "body", "buffer", "bus", "case", "component",
				"configuration", "constant", "disconnect", "downto",
				"else", "elsif", "end", "entity", "exit", "file", "for",
				"function", "generate", "generic", "group", "guarded",
				"if", "impure", "in", "inertial", "inout", "is", "label",
				"library", "linkage", "literal", "loop", "map", "mod",
				"nand", "new", "next", "nor", "not", "null", "of", "on",
				"open", "or", "others", "out", "package", "port",
				"postponed", "procedure", "process", "protected", "pure",
				"range", "record", "register", "reject", "rem", "report",
				"return", "rol", "ror", "select", "severity", "shared",
				"signal", "sla", "sll", "sra", "srl", "subtype", "then",
				"to", "transport", "type", "unaffected", "units", "until",
				"use", "variable", "wait", "when", "while", "with",
				"xnor", "xor",
				// ieee names the generated code depends on
				"ieee", "std_logic_1164", "numeric_std", "std_logic",
				"std_logic_vector", "std_ulogic", "unsigned", "signed",
				"rising_edge", "falling_edge", "resize", "to_unsigned"));

		/** The legalized VHDL name for the entity/architecture. */
		final String moduleName;
		/** Model identifier to VHDL identifier, in claim order. */
		private final Map<String, String> map =
				new LinkedHashMap<String, String>();
		/** Every claimed identifier, lowercased (VHDL is case-blind). */
		private final Set<String> used = new HashSet<String>();

		/**
		 * Claims VHDL identifiers for the module, ports, nets and register
		 * state variables, in that fixed order, so the mapping (and hence
		 * the output) is deterministic.
		 * @param model the model whose identifiers are legalized
		 */
		Names(HdlModel model) {

			moduleName = unique(sanitize(model.moduleName));
			for (HdlModel.Port port : model.ports()) {
				claim(port.name);
			}
			for (HdlModel.Net net : model.nets()) {
				claim(net.name);
			}
			for (HdlModel.Statement statement : model.statements()) {
				if (statement instanceof HdlModel.RegisterStatement) {
					claim(((HdlModel.RegisterStatement) statement).regName);
				}
			}
		} // end of constructor

		/**
		 * The VHDL identifier for a model identifier.
		 * @param modelName the model identifier to look up
		 * @return the claimed VHDL identifier
		 */
		String of(String modelName) {

			String id = map.get(modelName);
			if (id == null) {
				throw new IllegalStateException(
						"model name never claimed: " + modelName);
			}
			return id;
		} // end of of method

		/**
		 * Claim a fresh helper identifier (adder result signals).
		 * @param base the desired name
		 * @return the claimed, uniquified identifier
		 */
		String synth(String base) {

			return unique(sanitize(base));
		} // end of synth method

		/**
		 * Records a fresh VHDL identifier for a model name.
		 * @param modelName the model identifier to legalize and record
		 */
		private void claim(String modelName) {

			map.put(modelName, unique(sanitize(modelName)));
		} // end of claim method

		/**
		 * What the header documents: the walker's JLS-name renames
		 * composed with this pass, plus this pass's own changes to
		 * model names the walker did not rename - only entries whose
		 * two sides differ.
		 * @param model the model whose renames are composed
		 * @return JLS/model name to final VHDL identifier, in claim order
		 */
		Map<String, String> documentedRenames(HdlModel model) {

			Map<String, String> documented =
					new LinkedHashMap<String, String>();
			Map<String, String> walker = model.renames();
			for (Map.Entry<String, String> entry : walker.entrySet()) {
				String finalName = entry.getValue().equals(model.moduleName)
						? moduleName
						: map.getOrDefault(entry.getValue(),
								entry.getValue());
				if (!finalName.equals(entry.getKey())) {
					documented.put(entry.getKey(), finalName);
				}
			}
			for (Map.Entry<String, String> entry : map.entrySet()) {
				if (!entry.getKey().equals(entry.getValue())
						&& !walker.containsValue(entry.getKey())) {
					documented.put(entry.getKey(), entry.getValue());
				}
			}
			if (!moduleName.equals(model.moduleName)
					&& !walker.containsValue(model.moduleName)) {
				documented.put(model.moduleName, moduleName);
			}
			return documented;
		} // end of documentedRenames method

		/**
		 * The identifier, suffixed "_2", "_3", ... until its lowercased
		 * form is not already taken (VHDL is case-insensitive).
		 * @param id the candidate identifier
		 * @return a case-insensitively unique identifier
		 */
		private String unique(String id) {

			String candidate = id;
			int n = 2;
			while (!used.add(candidate
					.toLowerCase(java.util.Locale.ROOT))) {
				candidate = id + "_" + n;
				n += 1;
			}
			return candidate;
		} // end of unique method

		/**
		 * Underscore placement, first character, reserved words.
		 * @param name the candidate identifier to legalize
		 * @return the sanitized (but not yet uniquified) identifier
		 */
		private static String sanitize(String name) {

			StringBuilder sb = new StringBuilder(name.length());
			for (int i = 0; i < name.length(); i += 1) {
				char c = name.charAt(i);
				if (c == '_' && (sb.length() == 0
						|| sb.charAt(sb.length() - 1) == '_')) {
					continue; // no leading or doubled underscore
				}
				sb.append(c);
			}
			while (sb.length() > 0 && sb.charAt(sb.length() - 1) == '_') {
				sb.setLength(sb.length() - 1); // no trailing underscore
			}
			String id = sb.toString();
			if (id.isEmpty()) {
				id = "id";
			}
			else if (Character.isDigit(id.charAt(0))) {
				id = "id_" + id;
			}
			if (RESERVED.contains(id.toLowerCase(java.util.Locale.ROOT))) {
				// VHDL is case-insensitive, so the test is on the
				// lowercased form; "_v" keeps the result legal (a bare
				// "_" suffix would not be)
				id = id + "_v";
			}
			return id;
		} // end of sanitize method

	} // end of Names class

} // end of VhdlEmitter class
